openapi: 3.0.0

info:
  title: Rock OS Entities
  version: 2.0.0

tags:
- name: users
  description: users API

paths:
# [GET] users
  /users:
    get:
      security:
        - Bearer: []
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      security:
        - Bearer: []
      tags:
      - users
      summary: Add User
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      security:
        - Bearer: []
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      security:
        - Bearer: []
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        schema:
          type: integer
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      security:
        - Bearer: []
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /login:
    post:
      tags:
      - auth
      summary: authentication
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
components:
  schemas:
    users:
      type: object
      required:
          - email
          - password
      properties:
        email:
          type: string
          description: user Email
        password:
          type: string
          description: user Password


